#!/bin/sh
    
gfortran -O3 get_nres.f -c -o get_nres.og
gfortran -O3 assign_vdw_radii.f -c -o assign_vdw_radii.og
gfortran -O3 read_all_atom.f -c -o read_all_atom.og
gfortran -O3 rotation.f -c -o rotation.og

ar -rv prot_hole.lib get_nres.og
ar -rv prot_hole.lib assign_vdw_radii.og
ar -rv prot_hole.lib read_all_atom.og
ar -rv prot_hole.lib rotation.og

rm get_nres.og
rm assign_vdw_radii.og
rm read_all_atom.og
rm rotation.og

gfortran -O3 -fopenmp prot_hole_paral3.f prot_hole.lib -o prot_hole_paral3.xg









